version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: company_user_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db 
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: company_user_db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data:
